[workspace]
resolver = "2"

members = [
    # public models API
    "settings-models",

    # model-building tools
    "model-derive",
    "modeled-types",
    "scalar",
    "scalar-derive",
    "string_impls_for",

    # settings extensions
    "settings-extensions/autoscaling",
    "settings-extensions/aws",
    "settings-extensions/bootstrap-containers",
    "settings-extensions/cloudformation",
    "settings-extensions/container-registry",
    "settings-extensions/container-runtime",
    "settings-extensions/dns",
    "settings-extensions/ecs",
    "settings-extensions/host-containers",
    "settings-extensions/kernel",
    "settings-extensions/metrics",
    "settings-extensions/motd",
    "settings-extensions/network",
    "settings-extensions/ntp",
    "settings-extensions/oci-defaults",
    "settings-extensions/oci-hooks",
    "settings-extensions/pki",
    "settings-extensions/updates",
]
