//! Rust integration tests don't load modules by default.
//! This file is picked up by the integration tester and directs it to integration test submodules.
use anyhow::{Context, Result};
use bottlerocket_settings_sdk::model::AsTypeErasedModel;
use bottlerocket_settings_sdk::{Migrator, SettingsExtension};
pub use helpers::*;
use log::LevelFilter;

#[ctor::ctor]
fn setup_logging() {
    env_logger::builder()
        .filter_level(LevelFilter::Trace)
        .is_test(true)
        .init();
}

mod colliding_versions;
mod migration_validation;
mod motd;

/// We also define some helpers for invoking the CLI interface generated by the SDK.
mod helpers {
    use super::*;

    /// Wrapper around "extension.set" which uses the CLI.
    pub fn set_cli<Mi, Mo>(
        extension: SettingsExtension<Mi, Mo>,
        version: &str,
        value: serde_json::Value,
    ) -> Result<()>
    where
        Mi: Migrator<ModelKind = Mo>,
        Mo: AsTypeErasedModel,
    {
        extension
            .try_run_with_args(&[
                "extension",
                "proto1",
                "set",
                "--setting-version",
                version,
                "--value",
                value.to_string().as_str(),
            ])
            .context("Failed to run settings extension CLI")
            .map(|s| {
                assert!(s.is_empty());
                ()
            })
    }

    /// Wrapper around target migrations which uses the CLI.
    pub fn target_migrate_cli<Mi, Mo>(
        extension: SettingsExtension<Mi, Mo>,
        value: serde_json::Value,
        from_version: &str,
        target_version: &str,
    ) -> Result<serde_json::Value>
    where
        Mi: Migrator<ModelKind = Mo>,
        Mo: AsTypeErasedModel,
    {
        let value = value.to_string();
        let args = vec![
            "extension",
            "proto1",
            "migrate",
            "--value",
            &value,
            "--from-version",
            from_version,
            "--target-version",
            target_version,
        ];

        extension
            .try_run_with_args(args)
            .context("Failed to run settings extension CLI")
            .and_then(|s| {
                serde_json::from_str(s.as_str()).context("Failed to parse CLI result as JSON")
            })
    }

    /// Wrapper around flood migrations which uses the CLI.
    pub fn flood_migrate_cli<Mi, Mo>(
        extension: SettingsExtension<Mi, Mo>,
        value: serde_json::Value,
        from_version: &str,
    ) -> Result<serde_json::Value>
    where
        Mi: Migrator<ModelKind = Mo>,
        Mo: AsTypeErasedModel,
    {
        let value = value.to_string();
        let args = vec![
            "extension",
            "proto1",
            "flood-migrate",
            "--value",
            &value,
            "--from-version",
            from_version,
        ];

        extension
            .try_run_with_args(args)
            .context("Failed to run settings extension CLI")
            .and_then(|s| {
                serde_json::from_str(s.as_str()).context("Failed to parse CLI result as JSON")
            })
    }

    /// Wrapper around "extension.template_helper" which uses the CLI.
    pub fn template_helper_cli<Mi, Mo>(
        extension: SettingsExtension<Mi, Mo>,
        version: &str,
        helper_name: &str,
        args: Vec<serde_json::Value>,
    ) -> Result<serde_json::Value>
    where
        Mi: Migrator<ModelKind = Mo>,
        Mo: AsTypeErasedModel,
    {
        let template_args: Vec<String> = args
            .into_iter()
            .map(|arg| vec!["--arg".to_string(), arg.to_string()])
            .flatten()
            .collect();

        let args = [
            "extension",
            "proto1",
            "helper",
            "--setting-version",
            version,
            "--helper-name",
            helper_name,
        ]
        .into_iter()
        .map(str::to_string)
        .chain(template_args)
        .collect::<Vec<_>>();

        extension
            .try_run_with_args(args)
            .context("Failed to run settings extension CLI")
            .and_then(|s| {
                serde_json::from_str(s.as_str()).context("Failed to parse CLI result as JSON")
            })
    }
}
